server:
  port: 8080

spring:
  application:
    name: dans-eureka-gateway
  cloud:
    gateway:
#      server:
#        webflux:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service-route
          uri: lb://dans-eureka-user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1

        - id: auth-service-route
          uri: lb://dans-eureka-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
